apiVersion: apps/v1
kind: Deployment
metadata:
  name: caas-test-app
  labels:
    app: caas-test-app
    version: v1.0.0
    framework: radfish
spec:
  replicas: 2
  selector:
    matchLabels:
      app: caas-test-app
  template:
    metadata:
      labels:
        app: caas-test-app
        version: v1.0.0
        framework: radfish
    spec:
      containers:
      - name: caas-test-app
        # Google Artifact Registry path
        # Format: us-central1-docker.pkg.dev/PROJECT-ID/REPO-NAME/caas-test-app:latest
        image: "us-central1-docker.pkg.dev/caas-test-project/caas-test-repo/caas-test-app:latest"
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: PORT
          value: "8080"
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1001
          readOnlyRootFilesystem: false
      securityContext:
        fsGroup: 1001
---
apiVersion: v1
kind: Service
metadata:
  name: caas-test-app-service
  labels:
    app: caas-test-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: caas-test-app
